{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: ma-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        mysql_root_password: {{ $playbook.mysql.root_password }}
        mysql_port: {{ $playbook.mysql.port }}
        {{- if $playbook.mysql.databases }}
        mysql_databases:
          {{- toYaml $playbook.mysql.databases | nindent 10 }}
        {{- end }}
        {{- if $playbook.mysql.users }}
        mysql_users:
          {{- toYaml $playbook.mysql.users | nindent 10 }}
        {{- end }}
        mysql_daemon: mariadb
        {{- if $playbook.telegraf }}
        telegraf_agent_hostname: ms-{{ .Release.Name }}
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: mysql
            config:
              - servers = ["root:{{ $playbook.mysql.root_password }}@tcp(127.0.0.1:{{ $playbook.mysql.port }})/?tls=false"]
              - insecure_skip_verify = true
        {{- end }}

      roles:
        - role: onecloud-mysql
        {{- if $playbook.telegraf }}
        - role: ansible-telegraf
        {{- end }}
  requirements: |
    - name: onecloud-mysql
      src: https://iso.yunion.cn/vm-images/ansible-role-mysql-v0.0.3-yn.tar.gz
      type: file
    {{- if $playbook.telegraf }}
    - src: https://iso.yunion.cn/vm-images/ansible-telegraf-1.0.1.tar.gz
      name: ansible-telegraf
      type: file
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true
    {{- end }}

