{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: ix-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        influxdb_version: 1.8.0
        influxdb_admin_username: {{ $playbook.influxdb.adminUsername }}
        influxdb_admin_password: {{ $playbook.influxdb.adminPassword }}
        influxdb_config: true
        influxdb_http:
          auth_enabled: true
          bind_address: ""
          bind_port: {{ $playbook.influxdb.http_port }}
        influxdb_databases:
          {{- toYaml $playbook.influxdb.databases | nindent 10 }}
        influxdb_users:
          {{- toYaml $playbook.influxdb.databases | nindent 10 }}
        {{- if $playbook.telegraf }}
        telegraf_agent_hostname: ng-{{ .Release.Name }}
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: influxdb
            config:
              - urls = ["http://localhost:{{ $playbook.influxdb.http_port }}/debug/vars"]
              - username = "{{ $playbook.influxdb.adminUsername }}"
              - password = "{{ $playbook.influxdb.adminPassword }}"
              - insecure_skip_verify = true
        {{- end }}

      roles:
        - role: mrlesmithjr.ansible_bootstrap_python
        - role: ansible-influxdb
        {{- if $playbook.telegraf }}
        - role: ansible-telegraf
        {{- end }}
  requirements: |
    - src: mrlesmithjr.ansible_bootstrap_python
    - src: https://github.com/yunionio/ansible-influxdb
    {{- if $playbook.telegraf }}
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true
    {{- end }}

