{{- $name := .Release.Name -}}
{{- $node := .Values.virtualMachine -}}
{{- $desc := "InfluxDB" }}
{{- $needEipHypers := list "aliyun" "qcloud" "azure" "aws" "huawei" "ucloud" "google" "openstack" "zstack"}}
{{- $imageDict := dict "aliyun" "CentOS  7.3 64位" "huawei" "CentOS 7.3 64bit" "qcloud" "CentOS 7.3 64位" "aws" "CentOS 7 x86_64 GenericCloud 1808" "azure" "CentOS-7.7-7.7.2020100800" "google" "centos-7-v20200811" }} {{- $image := get $imageDict .Values.hypervisor }}
{{- if eq $image ""}}
{{- $image = "CentOS-7.6.1810-20190430.qcow2" }}
{{- end }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: ix-{{ $name }}
spec:
  description: {{ $desc }}
  projectConfig:
    project: {{ .Values.project }}
  vmConfig:
    {{- if .Values.preferManager }} 
    preferManager: {{ .Values.preferManager }} 
    {{- end }}
    {{- if .Values.preferRegion }} 
    preferRegion: {{ .Values.preferRegion }} 
    {{- end }}
    {{- if .Values.preferZone }} 
    preferZone: {{ .Values.preferZone }} 
    {{- end }}
    {{- if $node.preferHost }} 
    preferHost: {{ $node.preferHost }} 
    {{- end }}
    hypervisor: {{ .Values.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      {{- if $node.image }}
      image: {{ $node.image }}
      {{- else }}
      image: {{ $image }}
      {{- end }}
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if .Values.network }}
    networks:
      - network: {{ .Values.network }}
    {{- end }}

  {{- if or $node.newEipBw $node.newEipChargeType }}
  newEip:
    {{- if $node.newEipBw }}
    bw: {{ $node.newEipBw }}
    {{- end }}
    {{- if $node.newEipChargeType }}
    chargeType: {{ $node.newEipChargeType }}
    {{- end }}
  {{- else if $node.eip }}
  eip: $node.eip
  {{- else if eq .Values.vpc "default" }}
  {{- else if not (empty .Values.vpc) }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if has .Values.hypervisor $needEipHypers }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- end}}
  
