# cluster
project: "system"
preferManager: ""
preferRegion: ""
preferZone: ""
hypervisor: "kvm"
network: ""
virtualMachine:
  preferHost: ""
  # 主机的套餐，不能和 vcpuCount或者vmemSize 同时指定
  instanceType: ""
  # 不能和instanceType同时指定，否则instanceType优先生效
  vcpuCount: 1
  vmemSizeGB: 1
  
  # 系统盘镜像大小
  diskSizeGB: 30 
  # 系统镜像
  image: "" 
  # 存储后端类型
  storageBackend: "local"
  
  # 新建EIP并绑定
  # EIP的带宽
  # newEipBw: 100
  # EIP的付费类型
  # newEipChargeType: traffic
  # 已经存在的EIP的ID或者Name
  # eip: ""
  
  # 安全组，type: []string
  # secgroups:
  
  ansiblePlaybook:
    mysql: 
      root_password: Super_P@s$0rd
      port: 3306
      databases: [] 
        # - name: example_db
        #   encoding: latin1
        #   collation: latin1_general_ci
      users: []
        # - name: example2_user
        #   host: "%"
        #   password: Sime32_U$er_p@ssw0rd
        #   priv: "example2_db.*:ALL"
    telegraf:
      # required
      influxdbUrl: ""
      influxdbName: telegraf
