{{- $namespace := .Release.Namespace }}
{{- $name := .Release.Name }}
{{- $values := .Values }}
{{- $count := .Values.virtualMachines.slaveNode.count }}
{{- with .Values.virtualMachines.masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybook
metadata:
  name: rd-{{ $name }}-pk
spec:
  playbookTemplateRef:
    name: rd-{{ $name }}-pktem
  inventory:
    - virtualMachine:
        name: rd-{{ $name }}-master
      vars:
        redis_slave:
          value: "false"
    {{- range $i, $e := until ($count | int) }}
    - virtualMachine:
        name: rd-{{ $name }}-slave{{ add $e 1 }}
      vars:
        redis_slave: 
          value: "true"
    {{- end }}
  vars:
    redis_master_hostname:
      reference:
        kind: VirtualMachine
        namespace: {{ $namespace }}
        name: rd-{{ $name }}-master
        fieldPath: Status.ExternalInfo.Ips[0]
    onecloud_vm_id:
      reference:
        kind: VirtualMachine
        namespace: {{ $namespace }}
        name: rd-{{ $name }}-master
        fieldPath: Status.ExternalInfo.Id
    {{- if $values.envs.project_id }}
    onecloud_tenant_id:
      value: {{ $values.envs.project_id }}
    {{- end }}
    {{- if $values.envs.domain_id }}
    onecloud_domain_id:
      value: {{ $values.envs.domain_id }}
    {{- end }}
  maxRetryTimes: 2
{{- end}}

