{{- $name := .Release.Name -}}
{{- $values := .Values }}
{{- $node := .Values.virtualMachines.slaveNode -}}
{{- $count := $node.count }}
{{- $needEipHypers := list "aliyun" "qcloud" "azure" "aws" "huawei" "ucloud" "google" "openstack" "zstack"}}
{{- $imageDict := dict "aliyun" "CentOS  7.3 64位" "huawei" "CentOS 7.3 64bit" "qcloud" "CentOS 7.3 64位" "aws" "CentOS 7 x86_64 GenericCloud 1808" "azure" "CentOS-7.7-7.7.2021020400" "google" "centos-7-v20200811" "huaweicloudstack" "PC_CentOS_7.5_64bit_new_2" }} {{- $image := get $imageDict .Values.hypervisor }}
{{- if eq $image ""}}
{{- $image = "CentOS-7.6.1810-20190430.qcow2" }}
{{- end }}
{{- range $i, $e := until ($count | int) }}
{{- $suffix := printf "%s%d" "slave" (add $e 1) }}
{{- $desc := printf "%s%d" "Redis slave node No." (add $e 1) }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: rd-{{ $name }}-{{ $suffix }}
spec:
  description: {{ $desc }}
  projectConfig:
    project: {{ $values.project }}
  vmConfig:
    {{- if $values.preferManager }} 
    preferManager: {{ $values.preferManager }} 
    {{- end }}
    {{- if $values.preferRegion }} 
    preferRegion: {{ $values.preferRegion }} 
    {{- end }}
    {{- if $values.preferZone }} 
    preferZone: {{ $values.preferZone }} 
    {{- end }}
    {{- if $node.preferHost }} 
    preferHost: {{ $node.preferHost }} 
    {{- end }}
    hypervisor: {{ $values.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      {{- if $node.image }}
      image: {{ $node.image }}
      {{- else }}
      image: {{ $image }}
      {{- end }}
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if $values.network }}
    networks:
      - network: {{ $values.network }}
    {{- end }}
  {{- if or $node.newEipBw $node.newEipChargeType }}
  newEip:
    {{- if $node.newEipBw }}
    bw: {{ $node.newEipBw }}
    {{- end }}
    {{- if $node.newEipChargeType }}
    chargeType: {{ $node.newEipChargeType }}
    {{- end }}
  {{- else if $node.eip }}
  eip: $node.eip
  {{- else if eq $values.vpc "default" }}
  {{- else if not (empty $values.vpc) }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if has $values.hypervisor $needEipHypers }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- end}}

---

{{- end }}
