{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: mg-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        mongodb_net_port: {{ $playbook.mongodb.port }}
        mongodb_user_admin_name: {{ $playbook.mongodb.user_admin_name }}
        mongodb_user_admin_password: {{ $playbook.mongodb.user_admin_password }}
        mongodb_root_admin_name: {{ $playbook.mongodb.root_admin_name }}
        mongodb_root_admin_password: {{ $playbook.mongodb.root_admin_password }}
        {{- if $playbook.telegraf }}
        telegraf_agent_hostname: mg-{{ .Release.Name }}
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: mongodb
            config:
              - servers = ["mongodb://{{ $playbook.mongodb.root_admin_name }}:{{ $playbook.mongodb.root_admin_password }}@127.0.0.1:{{ $playbook.mongodb.port }})"]
              - insecure_skip_verify = true
        {{- end }}

      roles:
        - role: undergreen.mongodb
        {{- if $playbook.telegraf }}
        - role: ansible-telegraf
        {{- end }}
  requirements: |
    - name: undergreen.mongodb
  {{- if $playbook.telegraf }}
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true
  {{- end }}

