{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: mg-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      tasks:
        - name: Check if backup
          stat:
            path: /etc/yum.repos.d/CentOS-Base.repo.bk
          register: bk_status

        - name: Backup origin repository
          command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bk
          when: bk_status.stat.exists == False
          failed_when: False

        - name: Add base repository
          yum_repository:
            name: base
            description: CentOS-$releasever - Base
            baseurl: "{{`{{ repo_url }}`}}/centos/$releasever/os/$basearch/"
            gpgcheck: yes
            gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
            file: CentOS-Base

        - name: Add updates repository
          yum_repository:
            name: updates
            description: CentOS-$releasever - Updates
            baseurl: "{{`{{ repo_url }}`}}/centos/$releasever/updates/$basearch/"
            gpgcheck: yes
            gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
            file: CentOS-Base

        - name: Setup MongoDB 
          include_role:
            name: undergreen.mongodb
          vars:
            mongodb_version: "5.0"
            mongodb_repo: "{{`{{ repo_url }}`}}/mongodb/yum/el$releasever"
            pypi_custom_host: "{{`{{ repo_url }}`}}"
            mongodb_pymongo_pip_version: 3.12.0
            mongodb_net_port: {{ $playbook.mongodb.port }}
            mongodb_user_admin_name: {{ $playbook.mongodb.user_admin_name }}
            mongodb_user_admin_password: {{ $playbook.mongodb.user_admin_password }}
            mongodb_root_admin_name: {{ $playbook.mongodb.root_admin_name }}
            mongodb_root_admin_password: {{ $playbook.mongodb.root_admin_password }}

        - name: Setup Telegraf
          include_role:
            name: ansible-telegraf
          vars:
            telegraf_agent_version: 1.19.2-yn~fe11a96b
            telegraf_agent_version_patch: 0
            telegraf_agent_package_method: offline
            telegraf_agent_package_local_dir: /opt/yunion/ansible-install-pkg
            telegraf_agent_hostname: mg-{{ .Release.Name }}
            telegraf_global_tags:
              - tag_name: release_name
                tag_value: {{ .Release.Name }}
            telegraf_agent_output:
              - type: influxdb
                config:
                  - urls = ["{{`{{ influxdb_url }}`}}"]
                  - database = "telegraf"
                  - insecure_skip_verify = true
            telegraf_plugins_default:
              - plugin: mongodb
                config:
                  - servers = ["mongodb://{{ $playbook.mongodb.root_admin_name }}:{{ $playbook.mongodb.root_admin_password }}@127.0.0.1:{{ $playbook.mongodb.port }})"]
                  - insecure_skip_verify = true
  requirements: |
    - name: undergreen.mongodb
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true

