{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: ng-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        nginx_vhosts:
          - listen: "18081"
            filename: "telegraf.conf"
            server_name: N/A
            extra_parameters: |
              location /server_status {
                stub_status on;
                access_log   off;
                allow 127.0.0.1;
                deny all;
              }

        telegraf_agent_hostname: ng-{{ .Release.Name }}
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: nginx
            config:
              - urls = ["http://localhost:18081/server_status"]
              - insecure_skip_verify = true

      roles:
        - role: geerlingguy.nginx
        - role: ansible-telegraf
  requirements: |
    - src: geerlingguy.nginx
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: nginx_vhosts
      required: false
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true

