{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: ms-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        {{- if $playbook.postgresql.databases }}
        postgresql_databases:
          {{- toYaml $playbook.postgresql.databases | nindent 10 }}
        {{- end }}
        {{- if $playbook.postgresql.users }}
        postgresql_users:
          {{- toYaml $playbook.postgresql.users | nindent 10 }}
        {{- end }}
        {{- if $playbook.telegraf }}
        telegraf_agent_hostname: ms-{{ .Release.Name }}
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: postgresql
            config:
              - address = "postgres://postgres@127.0.0.1:5432?sslmode=disable"
        {{- end }}

      roles:
        - role: geerlingguy.postgresql
        {{- if $playbook.telegraf }}
        - role: ansible-telegraf
        {{- end }}
  requirements: |
    - name: geerlingguy.postgresql
  {{- if $playbook.telegraf }}
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true
  {{- end }}

