{{- $masterNode := .Values.virtualMachines.masterNode }}
{{- $playbook := $masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: rm-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        {{- if $playbook.rabbitmq.config }}
        rabbitmq_config:
          {{- toYaml .playbook.rabbitmq.config | nindent 8 }}
        {{- end }}
        rabbitmq_enable_clustering: true
        rabbitmq_master: rm-{{ .Release.Name }}-master
        rabbitmq_debian_version: {{ $playbook.rabbitmq.debian_version }}
        rabbitmq_redhat_version: {{ $playbook.rabbitmq.redhat_version }}
        rabbitmq_listen_port: {{ $playbook.rabbitmq.listen_port }}
        {{- if $playbook.rabbitmq.extra_vhosts }}
        rabbitmq_extra_vhosts: 
          {{- toYaml .playbook.rabbitmq.extra_vhosts | nindent 8 }}
        {{- end }}
        rabbitmq_users:
          - name: {{ $playbook.rabbitmq.adminUsername }}
            password: {{ $playbook.rabbitmq.adminPassword }}
            vhost: /
            configure_priv: ".*"
            read_priv: ".*"
            write_priv: ".*"
            tags: administrator
        tenegraf_agent_hostname: rm-{{ .Release.Name }}-master
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: rabbitmq
            config:
              - username = "{{ $playbook.rabbitmq.adminUsername }}"
              - password = "{{ $playbook.rabbitmq.adminPassword }}"

      tasks:
        - include_role:
            name: mrlesmithjr.rabbitmq 
        - include_role:
            name: ansible-telegraf
          when: inventory_hostname == rabbitmq_master
  requirements: |
    - src: mrlesmithjr.rabbitmq
    - src: https://github.com/yunionio/ansible-telegraf
  vars:
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true

