{{- $namespace := .Release.Namespace }}
{{- $name := .Release.Name }}
{{- $count := .Values.virtualMachines.slaveNode.count }}
{{- with .Values.virtualMachines.masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybook
metadata:
  name: rm-{{ $name }}-pk
spec:
  playbookTemplateRef:
    name: rm-{{ $name }}-pktem
  inventory:
    - virtualMachine:
        name: rm-{{ $name }}-master
    {{- range $i, $e := until ($count | int) }}
    - virtualMachine:
        name: rm-{{ $name }}-slave{{ add $e 1 }}
    {{- end }}
  vars:
    onecloud_vm_id:
      reference:
        kind: VirtualMachine
        namespace: {{ $namespace }}
        name: rm-{{ $name }}-master
        fieldPath: Status.ExternalInfo.Id
  maxRetryTimes: 5
{{- end}}

