{{- $name := .Release.Name -}}
{{- $node := .Values.virtualMachines.masterNode -}}
{{- $suffix := "master" }}
{{- $desc := "Rabbitmq master node" }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: rm-{{ $name }}-{{ $suffix }}
spec:
  description: {{ $desc }}
  projectConfig:
    project: {{ .Values.project }}
  vmConfig:
    {{- if .Values.preferManager }} 
    preferManager: {{ .Values.preferManager }} 
    {{- end }}
    {{- if .Values.preferRegion }} 
    preferRegion: {{ .Values.preferRegion }} 
    {{- end }}
    {{- if .Values.preferZone }} 
    preferZone: {{ .Values.preferZone }} 
    {{- end }}
    {{- if $node.preferHost }} 
    preferHost: {{ $node.preferHost }} 
    {{- end }}
    hypervisor: {{ .Values.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      {{- if $node.image }}
      image: {{ $node.image }}
      {{- else if eq .Values.hypervisor "azure" }}
      image: CentOS-CI-7.7.20191211
      {{- else }}
      image: CentOS-7.6.1810-20190430.qcow2
      {{- end }}
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if .Values.network }}
    networks:
      - network: {{ .Values.network }}
    {{- end }}

  {{- if or $node.newEipBw $node.newEipChargeType }}
  newEip:
    {{- if $node.newEipBw }}
    bw: {{ $node.newEipBw }}
    {{- end }}
    {{- if $node.newEipChargeType }}
    chargeType: {{ $node.newEipChargeType }}
    {{- end }}
  {{- else if $node.eip }}
  eip: $node.eip
  {{- else if eq .Values.hypervisor "aliyun" }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "qcloud" }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "azure" }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "aws" }}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "huawei"}}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "ucloud"}}
  newEip:
    bw: 100
    chargeType: traffic
  {{- else if eq .Values.hypervisor "google"}}
  newEip:
    bw: 100
    chargeType: traffic
  {{- end}}
  
