{{- $playbook := .Values.virtualMachines.masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: jk-{{ .Release.Name }}-pktem-master
spec:
  playbook: |
    - hosts: all
      become: true

      vars:
        jenkins_plugins:
          - swarm
        jenkins_plugin_timeout: 200
        jenkins_version: "2.204"
        {{- if $playbook.telegraf }}
        telegraf_agent_hostname: jk-{{ .Release.Name }}-master
        telegraf_global_tags:
          - tag_name: release_name
            tag_value: {{ .Release.Name }}
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["{{ $playbook.telegraf.influxdbUrl }}"]
              - database = "{{ $playbook.telegraf.influxdbName }}"
              - insecure_skip_verify = true
        telegraf_plugins_default:
          - plugin: jenkins
            config:
              - url = "http://{{ $playbook.jenkins.hostname }}:{{ $playbook.jenkins.httpPort }}"
              - username = "{{ $playbook.jenkins.adminUsername }}"
              - password = "{{ $playbook.jenkins.adminPassword }}"
              - insecure_skip_verify = true
              - response_timeout = "5s"
        {{- end }}

      roles:
        - role: geerlingguy.java
        - role: ansible-role-jenkins
        {{- if $playbook.telegraf }}
        - role: ansible-telegraf
        {{- end }}
  requirements: |
    - src: https://iso.yunion.cn/vm-images/ansible-role-java-2.1.0.tar.gz
      name: geerlingguy.java
      type: file
    - src: https://iso.yunion.cn/vm-images/ansible-role-jenkins-v0.0.2-yn.tar.gz
      name: ansible-role-jenkins
      type: file
    {{- if $playbook.telegraf }}
    - src: https://iso.yunion.cn/vm-images/ansible-telegraf-1.0.1.tar.gz
      name: ansible-telegraf
      type: file
    {{- end }}
  vars:
    - name: jenkins_hostname
      default: localhost
    - name: jenkins_http_port
      default: 8080
    - name: jenkins_admin_username
      default: admin
    - name: jenkins_admin_password
      default: admin
    {{- if $playbook.telegraf }}
    - name: onecloud_vm_id  
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true
    {{- end }}


{{- $count := .Values.virtualMachines.slaveNode.count }}
{{- if $count }}
---

apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: jk-{{ .Release.Name }}-pktem-slave
spec:
  playbook: |
    - hosts: all
      become: true

      roles:
        - role: geerlingguy.java
        - role: ansible-role-jenkins-slave
  requirements: |
    - src: geerlingguy.java
    - src: https://github.com/yunionio/ansible-role-jenkins-slave
  vars:
    - name: jenkins_slave_name
      required: true
    - name: jenkins_master_hostname
      required: true
    - name: jenkins_master_port
      default: 8080
    - name: jenkins_master_username
      default: admin
    - name: jenkins_master_password
      default: admin

{{- end }}
