{{- $namespace := .Release.Namespace }}
{{- $name := .Release.Name }}
{{- $values := .Values }}
{{- with .Values.virtualMachines.masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybook
metadata:
  name: jk-{{ $name }}-pk-master
spec:
  playbookTemplateRef:
    name: jk-{{ $name }}-pktem-master
  inventory:
    - virtualMachine:
        name: jk-{{ $name }}-master
  vars:
    jenkins_hostname: 
      value: {{ .jenkins.hostname }}
    jenkins_http_port:  
      value: {{ .jenkins.httpPort }}
    jenkins_admin_username: 
      value: {{ .jenkins.adminUsername }}
    jenkins_admin_password: 
      value: {{ .jenkins.adminPassword }}
    onecloud_vm_id:
      reference:
        kind: VirtualMachine
        namespace: {{ $namespace }}
        name: jk-{{ $name }}-master
        fieldPath: Status.ExternalInfo.Id
    {{- if $values.envs.project_id }}
    onecloud_tenant_id:
      value: {{ $values.envs.project_id }}
    {{- end }}
    {{- if $values.envs.domain_id }}
    onecloud_domain_id:
      value: {{ $values.envs.domain_id }}
    {{- end }}
  maxRetryTimes: 2
{{- end}}


{{- $count := .Values.virtualMachines.slaveNode.count }}
{{- if $count }}
---

{{- with .Values.virtualMachines.masterNode.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybook
metadata:
  name: jk-{{ $name }}-pk-slave
spec:
  playbookTemplateRef:
    name: jk-{{ $name }}-pktem-slave
  inventory:
    {{- range $i, $e := until ($count | int) }}
    - virtualMachine:
        name: jk-{{ $name }}-slave{{ add $e 1 }}
      vars:
        jenkins_slave_name:
          value: slave{{ add $e 1 }}
    {{- end }}
  vars:
    jenkins_master_hostname:
      reference:
        kind: VirtualMachine
        namespace: {{ $namespace }}
        name: jk-{{ $name }}-master
        fieldPath: Status.ExternalInfo.Ips[0]
    jenkins_master_port:
      value: {{ .jenkins.httpPort }}
    jenkins_master_username:
      value: {{ .jenkins.adminUsername }}
    jenkins_master_password:
      value: {{ .jenkins.adminPassword }}
  maxRetryTimes: 2
{{- end }}
{{- end }}
