{{- $playbook := .Values.virtualMachine.ansiblePlaybook }}
apiVersion: onecloud.yunion.io/v1
kind: AnsiblePlaybookTemplate
metadata:
  name: cboard-{{ .Release.Name }}-pktem
spec:
  playbook: |
    - hosts: all
      become: true
      roles:
        - role: ansible-cboard
  requirements: |
    - src: https://iso.yunion.cn/vm-images/ansible-cboard-v0.0.1-yn.tar.gz
      name: ansible-cboard
      type: file
  vars:
    - name: port
      required: false
    - name: onecloud_vm_id
      required: true
    - name: onecloud_tenant_id
      required: true
    - name: onecloud_domain_id
      required: true

