{{- $name := .Release.Name -}}
{{- $node := .Values.virtualMachine -}}
{{- $desc := "CBoard" }}
apiVersion: onecloud.yunion.io/v1
kind: Endpoint
metadata:
  name: cboard-{{ $name }}
spec:
  name: cboard-{{ $name }}
  url:
    host:
      reference:
        kind: VirtualMachine
        name: cboard-{{ $name }}
        namespace: {{ .Release.namespace }}
        fieldPath: Status.ExternalInfo.Ips[0]
    port: {{ .Values.virtualMachine.ansiblePlaybook.cboard.port }}
    prefix: cboard
